#Find how much total money a person has by asking how many of each type they have.
penny = int(input("How many pennies do you have? "))
nickel = int(input("How many nickels do you have? "))
dimes = int(input("How many dimes do you have? "))
quarters = int(input("How many quarters do you have? "))
ones = int(input("How many ones do you have? "))
fives = int(input("How many fives do you have? "))
tens = int(input("How many tens do you have? "))
twenties = int(input("How many twenties do you have? "))
fifties = int(input("How many fifties do you have? "))
hundreds = int(input("How many hundreds do you have? "))
a = float(0.01 * penny)
b = float(0.05 * nickel)
c = float(0.10 * dimes)
d = float(0.25 * quarters)
e = float(1 * ones)
f = float(5 * fives)
g = float(10 * tens)
h = float(20 * twenties)
i = float(50 * fifties)
j = float(100 * hundreds)
total = a + b + c + d + e + f + g + h + i + j
print("Your total is $" + str(total))
