name = raw_input("What is your name? ").lower()
#letters = len(name)
#print(letters)
value = 0
a = 1
b = 3
c = 3
d = 2
e = 1
f = 4
g = 2
h = 4
i = 1
j = 8
k = 5
l = 1
m = 3
n = 1
o = 1
p = 3
q = 10
r = 1
s = 1
t = 1
u = 1
v = 4
w = 4
x = 8
y = 4
z = 10
count = name.count('a')
value += (a * count)
count = name.count('b')
value += (b * count)
count = name.count('c')
value += (c * count)
count = name.count('d')
value += (d * count)
count = name.count('e')
value += (e * count)
count = name.count('f')
value += (f * count)
count = name.count('g')
value += (g * count)
count = name.count('h')
value += (h * count)
count = name.count('i')
value += (i * count)
count = name.count('j')
value += (j * count)
count = name.count('k')
value += (k * count)
count = name.count('l')
value += (l * count)
count = name.count('m')
value += (m * count)
count = name.count('n')
value += (n * count)
count = name.count('o')
value += (o * count)
count = name.count('p')
value += (p * count)
count = name.count('q')
value += (q * count)
count = name.count('r')
value += (r * count)
count = name.count('s')
value += (s * count)
count = name.count('t')
value += (t * count)
count = name.count('u')
value += (u * count)
count = name.count('v')
value += (v * count)
count = name.count('w')
value += (w * count)
count = name.count('x')
value += (x * count)
count = name.count('y')
value += (y * count)
count = name.count('z')
value += (z * count)
print(value)
